- hosts: all
  become: yes
  vars_files:
    - "../group_vars/production/mysql_php.yml"
    - "../group_vars/production/vault.yml"
  roles:
  - { role: nginx, tags: ['nginx'] }
  - { role: php, tags: ['php'] }
  - { role: mysql, tags: ['mysql'] }

